[package]
name = "numenum"
version = "0.1.0"
authors = ["Andy Kurnia"]
edition = "2021"
license = "MIT"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 3

[dependencies]
